config/routes.rb
Rails.application.routes.draw do
  get 'user_meetups/create'
  get 'user_meetups/update'
  get 'meetups/show'
  get 'meetups/new'
  get 'meetups/index'
  get 'meetups/create'
  get 'meetups/update'
  get "meetups/:id/booking_confirmation", to: "bookings#booking_confirmation", as: :booking_confirmation_meetup
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :meetups do
    resources :user_meetups
    resource :chatroom, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end

    member do
      post 'create_chatroom'
      get 'confirmation' # Custom route for the confirmation page
    end
  end
  post "/join_meetup", to: "meetups#join", as: :join_meetup

end

app/models/meetup.rb
class Meetup < ApplicationRecord
  belongs_to :user, class_name: "User"

  has_many :user_meetups
  has_many :users, through: :user_meetups
  has_one :chatroom, dependent: :destroy
  after_create :create_chatroom

  def create_chatroom
    build_chatroom.save
  end

  # belongs_to :venue
  # has_many :users, through: :user_meetups
end

app/controllers/meetups_controller.rb
  class MeetupsController < ApplicationController
    # before_action :set_user

    def show
      @suggested_places = generate_suggested
      @meetup = Meetup.find(params[:id])
      @users = @meetup.users
      @coordinates = user_coordinates
      @meetup.centre_point_array = geocode_centre
      @markers = user_markers
      @centre_address = geocode_address(@meetup.centre_point_array)
      @centre_point = centre_point_object(@centre_address)
      # raise
    end

    def new
      @meetup = Meetup.new
    end

    def index
      @meetups = current_user.user_meetups.map(&:meetup)
      # @meetups = current_user.meetups
    end

    def create
      @meetup = Meetup.new(meetup_params)
      @meetup.passcode = passcode
      @meetup.user = current_user
      #  add location for initial user at signup
      if @meetup.save
        redirect_to meetup_path(@meetup), notice: 'Meetup created successfully.'
      else
        render :new
      end
    end

    def join
      passcode = params[:passcode]
      meetup = Meetup.find_by(passcode: passcode)

      if meetup
        redirect_to meetup_path(meetup)
      else
        flash[:alert] = "Invalid passcode. Please try again."
        redirect_to root_path
      end
    end

    def create_chatroom
      @meetup = Meetup.find(params[:id])
      # Create a chatroom with the same ID as the meetup
      @chatroom = Chatroom.find_or_create_by(meetup: @meetup)
      # Redirect to the chatroom's show page
      redirect_to meetup_chatroom_path(@meetup, @chatroom)
    end

    def confirmation
      @meetup = Meetup.find(params[:id])
      # You can add any confirmation-related information or logic here
      render 'confirmation'
    end

    def edit
      @meetup = Meetup.find(params[:id])
    end

    def update
      # This method for admin to change - PATCH
      @meetup = Meetup.find(params[:id])
      @meetup.update(meetup_params)
      if @meetup.save
        redirect_to meetup_path # unsure if this will work (meetup_path(@meetup)?)
      else
        render :new
      end
    end

    private

    def meetup_params
      params.require(:meetup).permit(:name, :event_date, :purpose, :location)
    end

    def passcode(length = 5)
      # create password, 5 digit rand numbers
      numbers = (0..9).to_a
      num_array = numbers.sample(length)
      num_array.join
    end

    def user_markers
      markers = @users.map do |user|
        {
          lat: user.latitude,
          lng: user.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: { user: user }),
          marker_html: render_to_string(partial: "marker")
        }
      end
      markers
    end

    def centre_point_object(centre_address)
      {
        lat: @meetup.centre_point_array[0],
        lng: @meetup.centre_point_array[1],
        centre_window_html: render_to_string(partial: "centre_window", locals: { centre: centre_address }),
        centre_marker_html: render_to_string(partial: "centre_marker")
      }
    end

    def user_coordinates
      coordinates = @users.map do |user|
        [user.latitude, user.longitude]
      end
      coordinates
    end

    def geocode_address(coordinates)
      results = Geocoder.search(coordinates)
      "#{results.first.street}, #{results.first.city}, #{results.first.postal_code}"
    end

    def geocode_centre
      Geocoder::Calculations.geographic_center(@coordinates)
    end

    def generate_suggested
      places_array = ["Scarlet - Sultry 1920s inspired cocktail bar with live jazz and indulgent small plates.",
                      "The Potting Shed - Rustic eatery set in a Victorian venue serving fresh garden-to-table British cuisine.",
                      "Petit Paris - Charming French bistro with checkerboard floors and strings of fairy lights.",
                      "East India Club - Colonial India inspired dining room featuring curries, tandoors and gin fizzes.",
                      "Dolce & Salato - Neighborhood Italian highlighting handmade pastas and wood-fired pizzas.",
                      "Old Tom's Pub - Classic British gastropub,fish & chips and bangers & mash with draft ales",
                      "Wilkes & Co - Sophisticated steakhouse in a converted 18th century townhouse.",
                      "Silk Road - Vibrant Turkish and Lebanese small plates meant for sharing.",
                      "Franklin & Sons - Jewish deli crafting hand sliced sandwiches, bagels and smoked fish.",
                      "The Copper Still - Whisky and Scotch flights paired with modern Scottish fare.",
                      "Platform 9 3/4 - Hogwarts-themed restaurant serving dishes inspired by the wizarding world.",
                      "The Upside Down - Demogorgon servers and food inspired by the horrors of the alternate dimension.",
                      "The Slaughtered Lamb - Ancient pub with foreboding wooden beams and pints of thick ale. Beware the werewolves",
                      "Luna Dorada - Colorful, zesty Mexican cantina with tequila samplers and live mariachi music on weekends.",
                      "Signor Verdi - Italian trattoria crafting roast meats, pastas and pizzas in a wood-burning oven.",
                      "Fat Tuesday's - New Orleans inspired Cajun and Creole cuisine like jambalaya, gumbo and crawfish boils.",
                      "Tsubaki Sushi - Elegant and modern sushi spot featuring rare fish flown in daily.",
                      "Chez Antoinette - Classic French fine dining in a baroque mirrored dining room.",
                      "The Huntsman - Classic British gastropub with hearty roasts, meat pies and bread puddings.",
                      "Black Truffle - Underground speakeasy with molecular gastronomy menu.",
                      "221B Baker Street - Immersive Sherlock Holmes themed restaurant with mystery-inspired dishes and drinks.",
                      "Cau - South American steakhouse with rodizio style grilled meats.",
                      "Two Fold - Contemporary pizza, interesting pizza toppings.",
                      "Casa Cuba - Cuban cuisine, buzzing eatery with mojitos and Latin music.",
                      "The Brewers Inn - Traditional British pub with a restaurant that serves classic pub fare.",
                      "Hood - Plant-based comfort food serving vegan versions of classic dishes.",
                      "Berenjak - Vibrant Persian restaurant inspired by the bustling bazaars of Tehran.",
                      "ClipClop - Wine bar focusing on natural and organic wines."]

      places_array.sample(5)
    end
  end

app/views/meetups/_centre_marker.html.erb
<%= image_tag "marker_centre_point.png", height: 56, width: 56, alt: "Centre Logo" %>

app/views/meetups/_centre_window.erb
<div class="map-card-centre">
  <h2>Centre Point</h2>
  <p id="centre"><%= centre %></p>
</div>

app/views/meetups/_info_window.erb
<div class="map-card">
  <h2><%= user.username %></h2>
  <div class="row">
    <div class="col-6">
    <% image_filename = "#{user.username}.png" %>
            <% if File.exist?(Rails.root.join('app', 'assets', 'images', image_filename)) %>
            <p id="avatar"><%= image_tag "#{user.username}.png", class: "avatar" %></p>
            <% else %>
              <p id="avatar"><%= image_tag "MeetupLinkAvatar.png", class: "avatar" %></p>
            <% end %>
    </div>
    <div class="col-6">
    <p id="address"><%= user.address %></p>
    </div>
  </div>
</div>

app/views/meetups/_marker.html.erb
<%= image_tag "marker_user_location.png", height: 48, width: 48, alt: "Logo" %>

app/views/meetups/_share_passcode.html.erb
<div class="container">
        <div class="share-options">
            <div class="social-media">
              <div class="icon-spacing" style="display: flex; justify-content: space-between;">
                <h3 class="fab fa-whatsapp"></h3>
                <h3 class="fab fa-instagram"></h3>
                <h3 class="fab fa-twitter"></h3>
                <h3 class="fab fa-facebook-f"></h3>
                <h3 class="fab fa-linkedin-in"></h3>
              
              </div>
            </div>
        </div>
    </div>

app/views/meetups/confirmation.html.erb
<div class="container-confirmation">


  <div class="text-container">
    <div class="booking-confirmation-card">
      <div class="booking-confirmation-card-inner">
        <h1>Your Meetup is confirmed!</h1>
        <div class="confirm-tick">
          <svg width="465" height="465" viewBox="0 0 465 465" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path id="tick" d="M67.9524 244.767L170.249 350.232C170.563 350.555 171.082 350.551 171.391 350.224L376.899 132.744" stroke="url(#paint0_linear_0_1)" stroke-width="25.6797" stroke-linecap="round" class="svg-elem-1"></path>
          <circle id="circle" cx="232.5" cy="232.5" r="221.636" stroke="url(#paint1_linear_0_1)" stroke-width="21.729" class="svg-elem-2"></circle>
          <defs>
          <linearGradient id="paint0_linear_0_1" x1="239.184" y1="116.007" x2="163.194" y2="326.194" gradientUnits="userSpaceOnUse">
          <stop stop-color="#84FAB0"></stop>
          <stop offset="1" stop-color="#8FD3F4"></stop>
          </linearGradient>
          <linearGradient id="paint1_linear_0_1" x1="407.715" y1="74.2736" x2="43.458" y2="366.627" gradientUnits="userSpaceOnUse">
          <stop stop-color="#8FD3F4"></stop>
          <stop offset="1" stop-color="#84FAB0"></stop>
          </linearGradient>
          </defs>
          </svg>
        </div>  
        <div class="link-buttons">
          <%= link_to "Home", root_path, class: "btn btn-primary-confview" %>
          <%= link_to "View meetups", meetups_path, class: "btn btn-primary-confview"%></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetups/create.html.erb
<h1>Meetups#create</h1>
<p>Find me in app/views/meetups/create.html.erb</p>

app/views/meetups/edit.html.erb
<div class="container">
  <h1>Edit your meetup</h1>
    <%= simple_form_for(@meetup) do |f| %>
        <%= f.input :name %>
        <%= f.input :event_date %>
        <%= f.input :purpose %>
        <%= f.input :location %>
        <%= f.submit %>
    <% end %>

    <div class="gradients-container">
    <div class="g1"></div>
    <div class="g2"></div>
    <div class="g3"></div>
    <div class="g4"></div>
    <div class="g5"></div>
    <div class="interactive"></div>
  </div>

  <div class="gradients-container">
    <div class="g1"></div>
    <div class="g2"></div>
    <div class="g3"></div>
    <div class="g4"></div>
    <div class="g5"></div>
    <div class="interactive"></div>
  </div>
</div>

app/views/meetups/index.html.erb
<div class="container-show-main">
  <div class="col-sm-4">

              <% @meetups.each do |meetup| %>
    <div class="card-meetup-info">
      <div class="card-meetup-info-inner">
        <div class="card-meetup-info-inner-content">
          <br>
          <p>Name: <%= meetup.name %></p><br>
          <p>Event Date: <%= meetup.event_date %></p><br>
          <!-- Add any other meetup attributes you want to display -->

          <!-- Add "View this Meetup" button -->
          <div class="d-flex justify-content-center"><%= link_to "View this Meetup", meetup_path(meetup), class: "btn btn-primary-confview" %></div>
          <br>
            <%= render "meetups/share_passcode" %>
        </div>
      </div>
    </div>
    <br>
  <% end %>
</div>
<%# </div> %>

app/views/meetups/new.html.erb
<div class="blue-background">
  <br>
  <div class="container">
  <h1>Create a Meetup</h1>
    <div class="card">
      <%= simple_form_for(@meetup) do |f| %>

          <%= f.input :name, input_html: {class: "form-input" } %>
          <%= f.input :event_date, input_html: {class: "form-input" } %>
      <br>
          <%= f.submit class: "form-submit button"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/meetups/show.html.erb
<div class="container-show-main">
  <div class="col-sm-4">
    <div class="card-meetup-info">
      <div class="card-meetup-info-inner">
        <div class="card-meetup-info-inner-content">
          <h1>THIS IS THE MEETUP</h1>
            <div class="meetup-details">
              <p>Name: <%= @meetup.name %></p>
              <p>Event Date: <%= @meetup.event_date %></p>
            </div>
            <div class="midl-logo">
              <%= image_tag "marker_centre_point_home.png", class: "centre-point-marker-show" %>
              <h2 style="font-size: 88px;">midl</h2>
            </div>
              <p><%= @centre_address %></p>
              <%# <p>Location: <%= @meetup.location</p> %>
              <!-- icons -->
              <h4><div style="display:flex;justify-content: center;"><a class="btn btn-primary-view" style="margin: 20px" data-controller="copy-passcode" data-passcode="<%= @meetup.passcode %>" data-chatroom-path="<%= meetup_chatroom_path(@meetup) %>">meetup link → <%= @meetup.passcode %></a>
              <% @meetup.id %><% @meetup.user_id %></div></h4>
              <div class="d-flex justify-content-center text-center">
            <%= render "meetups/share_passcode" %>
          </div>
            <%# </ul> %>
            <%# <div class="container-edit-button">
              <% if current_user == @meetup.user %>
                <%# <%= link_to "Edit Meetup", edit_meetup_path(@meetup), class: "btn btn-primary meetup-info" %>
              <%# <% end %>
            <%# </div> %>
        </div>
      </div>
    </div>

    <div class="meetup-buttons">
      <% if @meetup.users.include?(current_user) %>
        <div class="meetup-buttons-joined">
          <% user_meetup = current_user.user_meetups.find_by(meetup: @meetup) %>
              <div class="d-flex justify-content-center text-center">
                <%= button_to "Leave Meetup", meetup_user_meetup_path(@meetup, user_meetup), method: :delete, class: "btn btn-info-joined" %>
              </div>
          <div class="d-flex justify-content-center text-center">
            <%= link_to "Chat", meetup_chatroom_path(@meetup), method: :post, class: "btn btn-success-joined" %>
          </div>
        </div>
      <% else %>
        <div class="meetup-buttons-to-join">
          <%# <p class="text-center">Fancy joining this meetup?</p> %>
          <%# <div class="justify-content-center text-center"> %>
          <%= button_to "Join Meetup", meetup_user_meetups_path(@meetup), class: "btn btn-primary-join" %>
        </div>
      <% end %>
      <%# <div class="actions"> %>
        <%# <% if @meetup.users.include?(current_user) %>
          <%# <div class="d-flex justify-content-center text-center"> %>
            <%# <%= link_to "Chat", meetup_chatroom_path(@meetup), method: :post, class: "btn btn-success" %>
          <%# </div> %>
        <%# <% end %>
      <%# </div> %>
    </div>



    <%# <br> %>
    <%# <div class="actions"> %>
      <%# <% if @meetup.users.include?(current_user) %>
        <%# <div class="d-flex justify-content-center text-center"> %>
          <%# <%= link_to "Chat", meetup_chatroom_path(@meetup), method: :post, class: "btn btn-success" %>
        <%# </div> %>
      <%# <% end %>
    <%# </div> %>
    <div class="meetup-ppl-going">
      <div class="meetup-ppl-going-inner">
        <h2>WHO'S GOING?</h2>
        <div class="meetup-ppl-going-members">
          <% @meetup.users.each do |user| %>
            <div class="meetup-ppl-going-members-avatar">
              <% image_filename = "#{user.username}.png" %>
                <% if File.exist?(Rails.root.join('app', 'assets', 'images', image_filename)) %>
                  <%= image_tag image_filename, alt: "Avatar", class: "avatar-large" %>
                <% else %>
                  <%= image_tag "MeetupLinkAvatar2.png", alt: "Default Avatar", class: "avatar-large" %>
                <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-8">
    <div class="card-trip-map">
      <div style="height: 664px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-centre-value="<%= @centre_point.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

  <%# <div class="col-sm-1"> %>
    <%# <div class="card-trip"> %>
      <%# <h3>Who's going?</h3> %>
      <%# <ul> %>
        <%# <% @meetup.users.each do |user| %>
          <%# <li> %>
            <%# <% image_filename = "#{user.username}.png" %>
            <%# <% if File.exist?(Rails.root.join('app', 'assets', 'images', image_filename)) %>
              <%# <%= image_tag image_filename, alt: "Avatar", class: "avatar-large" %>
            <%# <% else %>
              <%# <%= image_tag "MEETUP_8ee3775c-1795-4273-a768-9fb16f09dcac-1.png", alt: "Default Avatar", class: "avatar-large" %>
            <%# <% end %>
            <%# <br> <!-- Add a line break for spacing --> %>
          <%# </li> %>
        <%# <% end %>
      <%# </ul> %>
    <%# </div> %>
  <%# </div> %>
<%# </div> %>

<div class="container-show-second">
  <div class="col-sm-12">
    <% if @meetup.users.include?(current_user) %>
      <div class="card-suggested-places">
        <div class="card-suggested-places-inner">
          <div class="confirm-suggested"><h1>SUGGESTED PLACES</h1>
            <ol>
              <% @suggested_places.each_with_index do |suggested_place, index| %>
                <div class="suggested-list">
                  <li>
                    <%= suggested_place %>
                  </li>
                  <%= link_to "Option #{index + 1}", confirmation_meetup_path(@meetup), method: :post, class: "btn btn-confirm" %>
                </div>
              <% end %>
            </ol>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/meetups/update.html.erb
<h1>Meetups#update</h1>
<p>Find me in app/views/meetups/update.html.erb</p>