config/routes.rb
Rails.application.routes.draw do
  get 'user_meetups/create'
  get 'user_meetups/update'
  get 'meetups/show'
  get 'meetups/new'
  get 'meetups/index'
  get 'meetups/create'
  get 'meetups/update'
  get "meetups/:id/booking_confirmation", to: "bookings#booking_confirmation", as: :booking_confirmation_meetup
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :meetups do
    resources :user_meetups
    resource :chatroom, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end

    member do
      post 'create_chatroom'
      get 'confirmation' # Custom route for the confirmation page
    end
  end
  post "/join_meetup", to: "meetups#join", as: :join_meetup

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :meetup
  before_create :set_name_from_meetup
  has_many :messages

  private

  def set_name_from_meetup
    self.name = meetup.name
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user! # Ensure the user is signed in

  def show
    @meetup = Meetup.find(params[:meetup_id])

    # Find the chatroom associated with the meetup
    @chatroom = @meetup.chatroom

    if @chatroom.nil?
      # Handle the case where no chatroom is associated with the meetup
      flash[:alert] = "Chatroom not found for this meetup."
      redirect_to @meetup
    else
      # Ensure the association is loaded
      @chatroom.messages.load
      @message = Message.new
    end
  end

  # This is the only create action you need
  def create
    @meetup = Meetup.find(params[:meetup_id])
    # Check if a chatroom already exists for the meetup
    if @meetup.chatroom
      redirect_to meetup_chatroom_path(@meetup, @meetup.chatroom), notice: 'A chatroom already exists for this meetup.'
    else
      # Create a new chatroom for the meetup and associate it with the meetup
      @chatroom = Chatroom.new(meetup: @meetup)

      if @chatroom.save
        redirect_to meetup_chatroom_path(@meetup, @chatroom), notice: 'Chatroom created successfully.'
      else
        flash[:error] = 'Failed to create chatroom.'
        render 'meetups/show'
      end
    end
  end



end

app/views/chatrooms/show.html.erb
<div class="container">
  <div class="rows">
    <!-- Empty space column (3 columns wide) on the left -->
    <div class="col-md-2">
    <br>
          <%= link_to "Back to Meetup", meetup_path(@meetup), class: "btn btn-primary-back" %>
    </div>
    <!-- Chatroom container column (6 columns wide) in the center -->
    <div class="col-md-8">
      <div class="chatroom" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>" data-current-user-id="<%= current_user.id %>">
        <h1>#<%= @chatroom.name %></h1>

        <div class="messages" data-chatroom-subscription-target="messages">
          <% @chatroom.messages.each do |message| %>
          <%= render "messages/message", message: message %>
          <% end %>
        </div>

        <%= simple_form_for([@meetup, @meetup.chatroom, @meetup.chatroom.messages.new], html: { class: "d-flex", data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, }) do |f| %>
          <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}", wrapper_html: { class: "flex-grow-1" } %>
          <%= f.submit "Send", class: "btn btn-custom btn-primary mb-3" %>
        <% end %>
      </div>
    </div>

    <!-- Empty space column (3 columns wide) on the right -->
    <div class="col-md-2"></div>
  </div>
</div>