config/routes.rb
Rails.application.routes.draw do
  get 'user_meetups/create'
  get 'user_meetups/update'
  get 'meetups/show'
  get 'meetups/new'
  get 'meetups/index'
  get 'meetups/create'
  get 'meetups/update'
  get "meetups/:id/booking_confirmation", to: "bookings#booking_confirmation", as: :booking_confirmation_meetup
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :meetups do
    resources :user_meetups
    resource :chatroom, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end

    member do
      post 'create_chatroom'
      get 'confirmation' # Custom route for the confirmation page
    end
  end
  post "/join_meetup", to: "meetups#join", as: :join_meetup

end

app/views/pages/home.html.erb
<div class="gradient-bg">
  <svg xmlns="http://www.w3.org/2000/svg">
    <defs>
      <filter id="goo">
        <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
        <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8" result="goo" />
        <feBlend in="SourceGraphic" in2="goo" />
      </filter>
    </defs>
  </svg>

  <div class="wrapper">
    <h2><%= image_tag "marker_centre_point_home.png", class: "centre-point-marker-home" %> midl</h2>

    <h1><span data-controller="typed-js"></span></h1>
      <div style= "text-align:center; display:flex" >
        <%= link_to "Create meetup", new_meetup_path, :class => "button" %>
        <!-- Input field for passcode -->
          <%= form_with(url: join_meetup_path, method: :post, remote: true) do |form| %>
          <%= form.text_field :passcode, placeholder: "Enter meetup link →", id: "passcode-input", style: "text-align: center;" %>
          <%= form.submit "Join meetup", class: "button" %>
        </div>
        <% end %>
    </div>

  <div class="gradients-container">
    <div class="g1"></div>
    <div class="g2"></div>
    <div class="g3"></div>
    <div class="g4"></div>
    <div class="g5"></div>
    <div class="interactive"></div>
  </div>

</div>